AWSTemplateFormatVersion: '2010-09-09'
Description: Stack for deployment of Metaflow Step Functions requirements

Resources:
  EventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service:
              - events.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AllowStepFunctions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: ExecuteStepFunction
                Effect: Allow
                Action:
                  - 'states:StartExecution'
                Resource: !Sub 'arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:*'
  StepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service:
              - states.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: BatchPerms
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: JobsPermissions
              Effect: Allow
              Action:
                - "batch:TerminateJob"
                - "batch:DescribeJobs"
                - "batch:DescribeJobDefinitions"
                - "batch:DescribeJobQueues"
                - "batch:RegisterJobDefinition"
              Resource: '*'
            - Sid: DefinitionsPermissions
              Effect: Allow
              Action:
                - "batch:SubmitJob"
              Resource:
                - !Ref "JobQueue"
                - !Sub arn:aws:batch:${AWS::Region}:${AWS::AccountId}:job-definition/*:*
        - PolicyName: CustomS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: BucketAccess
              Effect: Allow
              Action: s3:ListBucket
              Resource: !GetAtt 'MetaflowS3Bucket.Arn'
            - Sid: ObjectAccess
              Effect: "Allow"
              Action: 
                - "s3:*Object"
              Resource:
                - !GetAtt 'MetaflowS3Bucket.Arn'
                - !Join ['', [ !GetAtt 'MetaflowS3Bucket.Arn', '/*' ]]
        - PolicyName: AllowCloudwatch
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: CloudwatchLogDelivery
                Effect: Allow
                Action:
                  - "logs:CreateLogDelivery"
                  - "logs:GetLogDelivery"
                  - "logs:UpdateLogDelivery"
                  - "logs:DeleteLogDelivery"
                  - "logs:ListLogDeliveries"
                  - "logs:PutResourcePolicy"
                  - "logs:DescribeResourcePolicies"
                  - "logs:DescribeLogGroups"
                Resource: '*'
        - PolicyName: AllowEventBridge
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: RuleMaintenance
                Effect: Allow
                Action:
                  - "events:PutTargets"
                  - "events:DescribeRule"
                Resource: !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctionsGetEventsForBatchJobsRule"
              - Sid: PutRule
                Effect: Allow
                Action:
                  - "events:PutRule"
                Resource: !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:rule/StepFunctionsGetEventsForBatchJobsRule"
                Condition:
                  StringEquals: 
                    events:detail-type: "Batch Job State Change"
        - PolicyName: DynamoDB
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: Items
              Effect: Allow
              Action:
                - "dynamodb:PutItem"
                - "dynamodb:GetItem"
                - "dynamodb:UpdateItem"
              Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${StepFunctionsStateDDB}
  StepFunctionsStateDDB:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "pathspec"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pathspec"
          KeyType: "HASH"
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true